Add typescript
gadomski/heystac pull request #8
Opened 2024-10-28 19:49 UTC by Tammo-Feldmann

This touches a lot of the code base so we'd probably want to merge this asap. Happy to discuss if you have any questions.

2024-10-28 20:36 UTC, gadomski requested changes
I did a quick search-around for existing typescript definitions for the STAC spec, found https://github.com/blacha/stac-ts which seems like the best fit (it's the only hit for typescript on https://stacindex.org/ecosystem?language=TypeScript). Could/should we lean on that rather than defining our own?

2024-10-28 20:36 UTC, gadomski commented on app/catalog.json
> +      "heystacId": "microsoft-pc"
The `ident:attribute` syntax is used for [STAC extensions](https://stac-extensions.github.io/), so I'd like to keep it.

2024-10-28 20:36 UTC, gadomski commented on app/catalogs/[id]/page.tsx
> +
This is derived directly from the STAC specification, so at the least we should move the interface up to `app/catalogs` — or is there a more common place to store interfaces for a next.js app?

2024-10-28 20:36 UTC, gadomski commented on app/catalogs/[id]/page.tsx
> +}
Same as `Catalog`, this is an interface we'll re-use elsewhere so we should move it higher in `app/`.

2024-10-28 20:36 UTC, gadomski commented on app/catalogs/[id]/page.tsx
> +type LinkIdObject = { id: string };
```suggestion
type Params = { id: string };
```

2024-10-28 23:26 UTC, Tammo-Feldmann commented on app/catalog.json
> +      "heystacId": "microsoft-pc"
Makes sense. Thanks for the background.

2024-10-29 00:31 UTC, Tammo-Feldmann commented
I made the changes that you suggested. Good call on those.

2024-10-29 00:33 UTC, Tammo-Feldmann commented
I like https://github.com/blacha/stac-ts as another improvement. Haven't made that change yet, though. Need to call it for tonight.

2024-10-29 11:00 UTC, gadomski commented
> I like https://github.com/blacha/stac-ts as another improvement.

Word, make #12 to track.

2024-10-29 11:06 UTC, gadomski approved these changes

2024-10-29 11:06 UTC, gadomski commented on app/catalogs/[id]/page.tsx
> +import Root from "../../catalog.json";
This feels more clear to me (rather than aliasing the `Catalog` type below.

2024-10-29 11:07 UTC, gadomski commented
@Tammo-Feldmann are there any checks we should add to our CI? Or will the build system take care of that for us now?

2024-10-29 11:07 UTC, merged

2024-10-29 11:27 UTC, Tammo-Feldmann commented
> are there any checks we should add to our CI?
The type check at compile time is a good step in the right direction. I mean, there is a bunch of useful stuff out there but I don't know where you want to take this app. The obvious starting points would be Jest for unit tests and either Cypress or Playwright for e2e. A year ago I would have recommended Playwright pretty unequivocally and I still would if you want to test multiple languages with the same syntax/framework. Otherwise, Cypress now has component testing that obviates React Testing Library. That is a pretty nice thing to have together in the same framework and Cypress has made their UX really nice in the last few releases.

2024-10-29 13:19 UTC, gadomski commented
Excellent, glad we're good on the typescript side of things. I'll copy this recommendation to https://github.com/gadomski/heystac/issues/6